package ie.ciaran.ProgrammingForBigData.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class SpecialCharacters {
    public static ArrayList specialCharacters = new ArrayList(Arrays.asList(
            ".",
            ",",
            "!" ,
            "\"" ,
            "#" ,
            "$" ,
            "%" ,
            "'" ,
            "(" ,
            ")" ,
            "*" ,
            "+" ,
            "-" ,
            "." ,
            "/" ,
            "0" ,
            "1" ,
            "2" ,
            "3" ,
            "4" ,
            "5" ,
            "6" ,
            "7" ,
            "8" ,
            "9" ,
            ":" ,
            ";" ,
            "?",
            "[",
            "]",
            "_",
            "—" ,
            "‘" ,
            "’" ,
            "“" ,
            "”" ,
            "\uFEFF",
            " ",
            "«",
            "°n",
            "»",
            "@",
            "=",
            ""));
}
